name: SUI 3 Codes review

on:
  pull_request:
    branches:
      - development
      - master
  push:
    branches:
      - development
      - master

jobs:
#  fetch-repos:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout sui-docs repository
#        uses: actions/checkout@v3
#        with:
#          repository: wpmudev/sui-docs
#          path: ./sui-docs
#          ref: development
#
#      - name: Grant execute permission for sui-docs
#        run: chmod +x ./sui-docs
#
#      - name: Checkout sui-css repository
#        uses: actions/checkout@v3
#        with:
#         repository: wpmudev/sui-css
#         path: ./sui-docs/packages/sui-css
#         ref: development
#
#      - name: Checkout sui-icons repository
#        uses: actions/checkout@v3
#        with:
#          repository: wpmudev/sui-icons
#          path: ./sui-docs/packages/sui-icons
#          ref: development
#
#      - name: Checkout sui-react repository
#        uses: actions/checkout@v3
#        with:
#          path: ./sui-docs/packages/sui-react
#
#      - name: List content
#        run: pwd && ls
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: sui-docs
#          path: sui-docs
#          retention-days: 1

  code-testing:
#    needs: [fetch-repos]
    runs-on: ubuntu-latest
    steps:
#      - name: Download repos
#        uses: actions/download-artifact@v3
#        with:
#          name: sui-docs
#          path: ./sui-docs

      - name: Checkout sui-docs repository
        uses: actions/checkout@v3
        with:
          repository: wpmudev/sui-docs
          path: .
          ref: development


      - name: Grant execute permission for all files
        run: chmod +x .

#      - name: Checkout sui-css repository
#        uses: actions/checkout@v3
#        with:
#          repository: wpmudev/sui-css
#          path: ./packages/sui-css
#          ref: development

      - name: Checkout sui-icons repository
        uses: actions/checkout@v3
        with:
          repository: wpmudev/sui-icons
          path: ./packages/sui-icons
          ref: development


      - name: Checkout sui-react repository
        uses: actions/checkout@v3
        with:
          path: ./packages/sui-react


      - name: List content
        run: pwd && ls

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --force

      - name: Run tests
        run: npm run test

  code-linting:
#    needs: [fetch-repos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sui-docs repository
        uses: actions/checkout@v3
        with:
          repository: wpmudev/sui-docs
          path: .
          ref: development

      - name: Checkout sui-icons repository
        uses: actions/checkout@v3
        with:
          repository: wpmudev/sui-icons
          path: ./packages/sui-icons
          ref: development

      - name: Grant execute permission for all files
        run: chmod +x .

      - name: Checkout sui-react repository
        uses: actions/checkout@v3
        with:
          path: ./packages/sui-react
          fetch-depth: 0

      - name: List content
        run: pwd && ls

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Eslint Code Check
        run: eslint --ext .ts,.tsx ./packages/sui-react/
