name: Code Review

on:
  pull_request:
    branches:
      - development
      - master
  push:
    branches:
      - development
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

  code-testing:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Run code test
        run: npm run test -- --coverage

  code-linting:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Run code lint
        run: npm run lint
